### DISCUSSION TITLE
Hikari pool gets exhausted

### DISCUSSION THREAD

**Discussion by marinsimina** [pietermartin/sqlg#483] [Q&A] [answered]
1) I was getting Hikari pool exhausted. it turned out I was opening a new connection after calling g.tx().close().

2) How can I configure the hikari pool, if necessary? I am using the following in application.yaml to configure sqlg:
```
sqlg:
  dataSource:
    jdbc.url: ${url}
    jdbc.username: ${username}
    jdbc.password: ${password}
```
Thanks!
